"""
Analyze the velocity profile in the velocity log file generated by extract_velocity.sh

"""
import numpy as np
import matplotlib.pyplot as plt

infile = "../velocity.log"

vel = np.loadtxt(infile, delimiter=',', usecols=(1, 2))

plt.plot(vel[:, 0])
plt.plot(vel[:, 1])
plt.show()
